In [1]:
def divide():
    return 5/0
try:
    divide()
except:
    print("oops, you were dividing by zero!!")

oops, you were dividing by zero!!


In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
list=[(s+' '+v+' '+o+'.')for s in subjects for v in verbs for o in objects]
for t in list:
    print(t)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [3]:
import numpy as np
v=[1,2,3]
l=len(v)
n = np.array([v]*l)
s=n.T
k=[0,1,2]
g=np.power(s,k)
print(g)

[[1 1 1]
 [1 2 4]
 [1 3 9]]
